language: android
sudo: false
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-24
    - android-26
    - extra-android-support
    - extra-android-m2repository
script:
  ./gradlew build

